# Generated by Django 4.2.4 on 2023-09-04 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Balance Date'),
        ),
    ]
