# Generated by Django 4.2.4 on 2023-09-05 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_account_balance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('balance_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Balance Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account', verbose_name='Account')),
            ],
        ),
    ]
