# Generated by Django 4.2.4 on 2023-09-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_accountbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_date',
        ),
    ]
