# Generated by Django 4.2.4 on 2023-09-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_account_balance_remove_account_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=80, verbose_name='Description'),
        ),
    ]
